In [17]:
import pandas as pd

In [18]:
df = pd.read_parquet(r"C:\Users\boris\OneDrive\Documents\GitHub\infovis\projeccto\impacto_hidrico_de-_las_paltas\data\processed\info_agua_censo.parquet")
df

,region,provincia,comuna,comuna_bajo_umbral,area,p6_fuente_agua,p7_distrib_agua
0,5,58,5802,2,1,1.0,1.0
1,4,43,4303,2,2,1.0,1.0
2,11,112,11202,1,1,1.0,1.0
3,1,11,1101,2,1,1.0,1.0
4,8,83,8301,2,1,1.0,1.0
...,...,...,...,...,...,...,...
7664461,3,31,3101,2,1,1.0,1.0
7664462,14,142,14202,2,2,1.0,1.0
7664463,9,91,9105,2,2,1.0,1.0
7664464,5,51,5101,2,1,1.0,1.0
7664465,13,131,13122,2,1,1.0,1.0

In [19]:
diccionario_censo = {
    'comuna_bajo_umbral': {
        1: 'Sí',
        2: 'No'
    },
    
    'area': {
        1: 'Urbano',
        2: 'Rural'
    },
    
    'p6_fuente_agua': {
        1: 'Red pública',
        2: 'Pozo o noria',
        3: 'Camión aljibe',
        4: 'Río, vertiente, estero, canal, lago, agua lluvia, etc.',
        -99: 'No respuesta',
        'NA': 'No aplica'
    },
    
    'p7_distrib_agua': {
        1: 'Con llave dentro de la vivienda',
        2: 'Con llave dentro del sitio, pero fuera de la vivienda',
        3: 'No tiene sistema, la acarrea',
        -99: 'No respuesta',
        'NA': 'No aplica'
    }
}

In [20]:
diccionario_region = {
    1: 'Tarapacá',
    2: 'Antofagasta',
    3: 'Atacama',
    4: 'Coquimbo',
    5: 'Valparaíso',
    6: "Libertador General Bernardo O'Higgins",
    7: 'Maule',
    8: 'Biobío',
    9: 'La Araucanía',
    10: 'Los Lagos',
    11: 'Aysén del General Carlos Ibáñez del Campo',
    12: 'Magallanes y de la Antártica Chilena',
    13: 'Metropolitana de Santiago',
    14: 'Los Ríos',
    15: 'Arica y Parinacota',
    16: 'Ñuble'
}

In [24]:
df.replace(diccionario_censo, inplace=True)

In [25]:
df.replace(diccionario_region, inplace=True)

In [26]:
df

,region,provincia,comuna,comuna_bajo_umbral,area,p6_fuente_agua,p7_distrib_agua
0,Valparaíso,58,5802,No,Urbano,Red pública,Con llave dentro de la vivienda
1,Coquimbo,43,4303,No,Rural,Red pública,Con llave dentro de la vivienda
2,Aysén del General Carlos Ibáñez del Campo,112,11202,Sí,Urbano,Red pública,Con llave dentro de la vivienda
3,Tarapacá,Aysén del General Carlos Ibáñez del Campo,1101,No,Urbano,Red pública,Con llave dentro de la vivienda
4,Biobío,83,8301,No,Urbano,Red pública,Con llave dentro de la vivienda
...,...,...,...,...,...,...,...
7664461,Atacama,31,3101,No,Urbano,Red pública,Con llave dentro de la vivienda
7664462,Los Ríos,142,14202,No,Rural,Red pública,Con llave dentro de la vivienda
7664463,La Araucanía,91,9105,No,Rural,Red pública,Con llave dentro de la vivienda
7664464,Valparaíso,51,5101,No,Urbano,Red pública,Con llave dentro de la vivienda
7664465,Metropolitana de Santiago,131,13122,No,Urbano,Red pública,Con llave dentro de la vivienda

In [27]:
df_conteo = df.groupby(['region', 'p6_fuente_agua']).size().reset_index(name='cantidad')
df_conteo

         region                                     p6_fuente_agua  cantidad
0   Antofagasta                                      Camión aljibe      7523
1   Antofagasta                                       No respuesta        61
2   Antofagasta                                       Pozo o noria       399
3   Antofagasta                                        Red pública    193706
4   Antofagasta  Río, vertiente, estero, canal, lago, agua lluv...       376
..          ...                                                ...       ...
75        Ñuble                                      Camión aljibe      5049
76        Ñuble                                       No respuesta        12
77        Ñuble                                       Pozo o noria     27256
78        Ñuble                                        Red pública    152864
79        Ñuble  Río, vertiente, estero, canal, lago, agua lluv...      2332

[80 rows x 3 columns]

In [30]:
df_aljibe = df_conteo[df_conteo['p6_fuente_agua'] == 'Camión aljibe']

In [31]:
df_aljibe

                                       region p6_fuente_agua  cantidad
0                                 Antofagasta  Camión aljibe      7523
5                          Arica y Parinacota  Camión aljibe      3989
10                                    Atacama  Camión aljibe     10192
15  Aysén del General Carlos Ibáñez del Campo  Camión aljibe        61
20                                     Biobío  Camión aljibe      7432
25                                   Coquimbo  Camión aljibe     16817
30                               La Araucanía  Camión aljibe     16817
35      Libertador General Bernardo O'Higgins  Camión aljibe      4272
40                                  Los Lagos  Camión aljibe      4159
45                                   Los Ríos  Camión aljibe      1909
50       Magallanes y de la Antártica Chilena  Camión aljibe      1169
55                                      Maule  Camión aljibe      5731
60                  Metropolitana de Santiago  Camión aljibe     10155
65                                   Tarapacá  Camión aljibe     11306
70                                 Valparaíso  Camión aljibe     24560
75                                      Ñuble  Camión aljibe      5049

In [35]:
df_ultimate = df_aljibe.reset_index()
df_ultimate

    index                                     region p6_fuente_agua  cantidad
0       0                                Antofagasta  Camión aljibe      7523
1       5                         Arica y Parinacota  Camión aljibe      3989
2      10                                    Atacama  Camión aljibe     10192
3      15  Aysén del General Carlos Ibáñez del Campo  Camión aljibe        61
4      20                                     Biobío  Camión aljibe      7432
5      25                                   Coquimbo  Camión aljibe     16817
6      30                               La Araucanía  Camión aljibe     16817
7      35      Libertador General Bernardo O'Higgins  Camión aljibe      4272
8      40                                  Los Lagos  Camión aljibe      4159
9      45                                   Los Ríos  Camión aljibe      1909
10     50       Magallanes y de la Antártica Chilena  Camión aljibe      1169
11     55                                      Maule  Camión aljibe      5731
12     60                  Metropolitana de Santiago  Camión aljibe     10155
13     65                                   Tarapacá  Camión aljibe     11306
14     70                                 Valparaíso  Camión aljibe     24560
15     75                                      Ñuble  Camión aljibe      5049

In [37]:
aaaa = df_ultimate.drop(columns = ["index", 'p6_fuente_agua'])
aaaa

                                       region  cantidad
0                                 Antofagasta      7523
1                          Arica y Parinacota      3989
2                                     Atacama     10192
3   Aysén del General Carlos Ibáñez del Campo        61
4                                      Biobío      7432
5                                    Coquimbo     16817
6                                La Araucanía     16817
7       Libertador General Bernardo O'Higgins      4272
8                                   Los Lagos      4159
9                                    Los Ríos      1909
10       Magallanes y de la Antártica Chilena      1169
11                                      Maule      5731
12                  Metropolitana de Santiago     10155
13                                   Tarapacá     11306
14                                 Valparaíso     24560
15                                      Ñuble      5049

In [ ]:
ruta_guardado = r"C:\Users\boris\OneDrive\Documents\GitHub\infovis\projeccto\impacto_hidrico_de-_las_paltas\visualizaciones\balanza\datos_camion_aljibe.json"

aaaa.to_json(
    ruta_guardado,
    orient='records',
    force_ascii=False,
    indent=4
)